name = "rfm-pwa"
pages_build_output_dir = "./dist"
compatibility_date = "2026-09-24"

[vars]
VAPID_PUBLIC_KEY = "BFPeQaiN9LB04gbRMwDGLrSajtYp3D_c4LBhBXG_jmAKxN9Uw0aUysusbD8Z7iRNdhjYHjsrq4NIANu2BKCFmEs"
VAPID_SUBJECT = "https://rallyfansmap.ru"
