export function basemapField(...names) {
  return ['to-string', ['coalesce', ...names.map(name => ['get', name]), '']];
}

export function basemapNumber(names, fallback = 0) {
  return ['to-number', ['coalesce', ...names.map(name => ['get', name]), fallback], fallback];
}

export function basemapTruthy(...names) {
  const value = basemapField(...names);
  return ['!', ['in', value, ['literal', ['', '0', 'false', 'no', 'none', 'null']]]];
}

export function featureMinZoom() {
  return basemapNumber(['min_zoom', 'minzoom'], 0);
}

export function featureSortRank(fallback = 0) {
  return basemapNumber(['sort_rank', 'rank'], fallback);
}

export function minZoomOpacity(opacity = 1) {
  const out = ['step', ['zoom'], 0];
  for (let z = 5; z <= 18; z++) {
    out.push(z, ['case', ['<=', featureMinZoom(), z], opacity, 0]);
  }
  return out;
}

export function basemapClass() {
  return basemapField(
    'kind',
    'kind_detail',
    'highway',
    'pmap:kind',
    'class',
    'type',
    'natural',
    'landuse',
    'amenity',
    'tourism',
    'shop',
  );
}

export function roadClass() {
  return basemapField('kind_detail', 'highway', 'pmap:kind', 'kind', 'class', 'type');
}

export function roadKind() {
  return basemapField('kind');
}

export function roadWidthAt(level, casing = 0) {
  const widths =
    level <= 6
      ? [
          'motorway',
          2.2,
          'motorway_link',
          1.65,
          'trunk',
          2,
          'trunk_link',
          1.5,
          'primary',
          1.7,
          'primary_link',
          1.3,
          'secondary',
          1.4,
          'secondary_link',
          1.1,
          'tertiary',
          1.1,
          'tertiary_link',
          0.9,
          0.7,
        ]
      : level <= 10
        ? [
            'motorway',
            4.2,
            'motorway_link',
            3.1,
            'trunk',
            3.8,
            'trunk_link',
            2.8,
            'primary',
            3.2,
            'primary_link',
            2.4,
            'secondary',
            2.7,
            'secondary_link',
            2,
            'tertiary',
            2.2,
            'tertiary_link',
            1.7,
            'residential',
            1.6,
            'service',
            1.2,
            'unclassified',
            1.4,
            'track',
            1.1,
            'path',
            0.9,
            'steps',
            0.8,
            1.3,
          ]
        : [
            'motorway',
            9,
            'motorway_link',
            6.5,
            'trunk',
            8,
            'trunk_link',
            5.8,
            'primary',
            7,
            'primary_link',
            5.2,
            'secondary',
            6,
            'secondary_link',
            4.5,
            'tertiary',
            5,
            'tertiary_link',
            3.8,
            'residential',
            4,
            'service',
            3,
            'unclassified',
            3.4,
            'road',
            3.2,
            'pedestrian',
            3,
            'track',
            2.4,
            'path',
            1.8,
            'footway',
            1.6,
            'sidewalk',
            1.4,
            'crossing',
            1.6,
            'cycleway',
            1.8,
            'bridleway',
            1.6,
            'steps',
            1.5,
            'driveway',
            2.2,
            'parking_aisle',
            2,
            'alley',
            2,
            'emergency_access',
            2,
            2.5,
          ];
  return [
    '+',
    ['*', ['match', roadClass(), ...widths], ['case', basemapTruthy('is_link'), 0.82, 1]],
    casing,
  ];
}

export function roadWidth(casing = 0) {
  return [
    'interpolate',
    ['linear'],
    ['zoom'],
    6,
    roadWidthAt(6, casing),
    10,
    roadWidthAt(10, casing),
    14,
    roadWidthAt(14, casing),
  ];
}

export function roadColor() {
  return [
    'match',
    roadClass(),
    'motorway',
    '#d98f49',
    'motorway_link',
    '#d99b5f',
    'trunk',
    '#dfa35a',
    'trunk_link',
    '#e1b270',
    'primary',
    '#e7bb6f',
    'primary_link',
    '#e8c58a',
    'secondary',
    '#ead191',
    'secondary_link',
    '#ead9a8',
    'tertiary',
    '#f1dfb1',
    'tertiary_link',
    '#f2e5c5',
    'residential',
    '#ffffff',
    'living_street',
    '#ffffff',
    'pedestrian',
    '#f5eee3',
    'service',
    '#f7f6f2',
    'unclassified',
    '#fbfaf6',
    'driveway',
    '#f4f1eb',
    'parking_aisle',
    '#f0ede7',
    'alley',
    '#f3efe9',
    'track',
    '#c9b48f',
    'path',
    '#b7a98d',
    'footway',
    '#b7a98d',
    'sidewalk',
    '#b9afa0',
    'crossing',
    '#9e9a91',
    'cycleway',
    '#93b7a0',
    'bridleway',
    '#b79c7d',
    'steps',
    '#9e968a',
    '#ebe8df',
  ];
}

export function landColor() {
  const sport = basemapField('sport');
  return [
    'case',
    ['!=', sport, ''],
    '#d2e2bd',
    [
      'match',
      basemapClass(),
      'forest',
      '#c9ddbd',
      'wood',
      '#c9ddbd',
      'scrub',
      '#d1dfc7',
      'grass',
      '#dce8c7',
      'grassland',
      '#dce8c7',
      'meadow',
      '#dce8c7',
      'park',
      '#d7e9c5',
      'national_park',
      '#cfe5c1',
      'nature_reserve',
      '#cfe5c1',
      'recreation_ground',
      '#d7e9c5',
      'farmland',
      '#eadfbd',
      'farm',
      '#eadfbd',
      'farmyard',
      '#e7d9bc',
      'orchard',
      '#dce4bf',
      'residential',
      '#e8e4dd',
      'commercial',
      '#e5dfdc',
      'retail',
      '#e5dfdc',
      'industrial',
      '#ddd8d4',
      'cemetery',
      '#d5dfcf',
      'military',
      '#ded9d0',
      'school',
      '#e8dfca',
      'college',
      '#e8dfca',
      'university',
      '#e8dfca',
      'kindergarten',
      '#e8dfca',
      'hospital',
      '#e8d7d8',
      'sand',
      '#eee2bd',
      'beach',
      '#f3e5b8',
      'wetland',
      '#c8ded2',
      'glacier',
      '#e5f0f2',
      'bare_rock',
      '#dedbd5',
      'runway',
      '#d4d2cf',
      'taxiway',
      '#dedbd8',
      'aerodrome',
      '#dedbd8',
      'pitch',
      '#d2e2bd',
      'stadium',
      '#d4e3c2',
      'golf_course',
      '#d7e5c9',
      '#e3e6db',
    ],
  ];
}

export function poiColor() {
  return [
    'match',
    basemapField('kind'),
    'fuel',
    '#d97838',
    'charging_station',
    '#64a36f',
    'parking',
    '#6f86a7',
    'bicycle_parking',
    '#6f86a7',
    'motorcycle_parking',
    '#6f86a7',
    'toilets',
    '#8a75a2',
    'shower',
    '#8a75a2',
    'drinking_water',
    '#4a90a8',
    'water_point',
    '#4a90a8',
    'hospital',
    '#c85f67',
    'clinic',
    '#c85f67',
    'pharmacy',
    '#c85f67',
    'doctors',
    '#c85f67',
    'dentist',
    '#c85f67',
    'fire_station',
    '#c85f67',
    'emergency_phone',
    '#c85f67',
    'viewpoint',
    '#7a6f55',
    'information',
    '#687c91',
    'camp_site',
    '#5f8a62',
    'caravan_site',
    '#5f8a62',
    'shelter',
    '#5f8a62',
    'alpine_hut',
    '#5f8a62',
    'wilderness_hut',
    '#5f8a62',
    'supermarket',
    '#8b6b9a',
    'convenience',
    '#8b6b9a',
    'grocery',
    '#8b6b9a',
    'cafe',
    '#a87a54',
    'restaurant',
    '#a87a54',
    'bakery',
    '#a87a54',
    'hotel',
    '#7d6a99',
    'motel',
    '#7d6a99',
    'guest_house',
    '#7d6a99',
    'hostel',
    '#7d6a99',
    'bed_and_breakfast',
    '#7d6a99',
    'station',
    '#657a92',
    'bus_stop',
    '#657a92',
    'aerodrome',
    '#657a92',
    'airfield',
    '#657a92',
    'peak',
    '#756b58',
    'landmark',
    '#756b58',
    'memorial',
    '#756b58',
    '#777f89',
  ];
}

export function poiIconExpression() {
  return [
    'match',
    basemapField('kind'),
    'fuel',
    '⛽',
    'charging_station',
    '⚡',
    'parking',
    'P',
    'bicycle_parking',
    'P',
    'motorcycle_parking',
    'P',
    'toilets',
    'WC',
    'shower',
    '◌',
    'drinking_water',
    '◉',
    'water_point',
    '◉',
    'hospital',
    '✚',
    'clinic',
    '✚',
    'pharmacy',
    '✚',
    'doctors',
    '✚',
    'dentist',
    '✚',
    'fire_station',
    '✚',
    'emergency_phone',
    '!',
    'viewpoint',
    '◉',
    'information',
    'i',
    'camp_site',
    '△',
    'caravan_site',
    '△',
    'shelter',
    '△',
    'alpine_hut',
    '△',
    'wilderness_hut',
    '△',
    'supermarket',
    '▣',
    'convenience',
    '▣',
    'grocery',
    '▣',
    'cafe',
    '●',
    'restaurant',
    '●',
    'bakery',
    '●',
    'hotel',
    '◆',
    'motel',
    '◆',
    'guest_house',
    '◆',
    'hostel',
    '◆',
    'bed_and_breakfast',
    '◆',
    'station',
    '▤',
    'bus_stop',
    '▤',
    'aerodrome',
    '✈',
    'airfield',
    '✈',
    'peak',
    '▲',
    'landmark',
    '◆',
    'memorial',
    '◆',
    '•',
  ];
}

export function waterClass() {
  return basemapField('kind_detail', 'kind');
}

export function waterWidth() {
  return [
    'interpolate',
    ['linear'],
    ['zoom'],
    6,
    [
      'match',
      waterClass(),
      'river',
      1.1,
      'canal',
      0.9,
      'stream',
      0.6,
      'drain',
      0.45,
      'ditch',
      0.4,
      0.7,
    ],
    10,
    [
      'match',
      waterClass(),
      'river',
      2.2,
      'canal',
      1.7,
      'stream',
      1.1,
      'drain',
      0.75,
      'ditch',
      0.65,
      1.2,
    ],
    14,
    ['match', waterClass(), 'river', 4.2, 'canal', 3, 'stream', 2, 'drain', 1.3, 'ditch', 1.1, 2],
  ];
}

export function boundaryWidth() {
  return [
    'interpolate',
    ['linear'],
    ['zoom'],
    5,
    [
      'match',
      basemapField('kind'),
      'country',
      1.5,
      'region',
      1,
      'county',
      0.7,
      'locality',
      0.5,
      0.6,
    ],
    10,
    [
      'match',
      basemapField('kind'),
      'country',
      2.3,
      'region',
      1.7,
      'county',
      1.2,
      'locality',
      0.8,
      1,
    ],
    14,
    [
      'match',
      basemapField('kind'),
      'country',
      3,
      'region',
      2.2,
      'county',
      1.6,
      'locality',
      1.1,
      1.3,
    ],
  ];
}
